-- Rebuild schema for the Portfolio_GTHR-Books_module Supabase project.
-- Run this in a NEW Supabase project's SQL editor.
--
-- This project still uses Supabase Auth and the Supabase REST API, so the
-- fastest recovery path is a new Supabase project backed by PostgreSQL.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.portfolioowner (
  id integer generated by default as identity primary key,
  name text not null,
  email text not null,
  linkedin_url text,
  github_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.navigationitems (
  id integer generated by default as identity primary key,
  text text not null,
  link text not null,
  is_button boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.herocontent (
  id integer generated by default as identity primary key,
  title text not null,
  span text,
  description text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.herosubtitles (
  id integer generated by default as identity primary key,
  subtitle_text text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.heroctas (
  id integer generated by default as identity primary key,
  text text not null,
  link text not null,
  icon text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.aboutcontent (
  id integer generated by default as identity primary key,
  title text not null,
  description text not null,
  image_src text,
  image_alt text,
  expertise_title text not null,
  cta_text text,
  cta_link text,
  cta_icon text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.aboutexpertise (
  id integer generated by default as identity primary key,
  about_id integer not null references public.aboutcontent(id) on delete cascade,
  expertise_item text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.resume (
  id integer generated by default as identity primary key,
  title text not null,
  intro text,
  cv_download_text text,
  cv_download_link text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.professionalexperience (
  id integer generated by default as identity primary key,
  resume_id integer not null default 1 references public.resume(id) on delete cascade,
  title text not null,
  company text not null,
  dates text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.experienceresponsibilities (
  id integer generated by default as identity primary key,
  experience_id integer not null references public.professionalexperience(id) on delete cascade,
  responsibility text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.education (
  id integer generated by default as identity primary key,
  resume_id integer not null default 1 references public.resume(id) on delete cascade,
  degree text not null,
  institution text not null,
  dates text not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.skills (
  id integer generated by default as identity primary key,
  resume_id integer not null default 1 references public.resume(id) on delete cascade,
  skill_name text not null,
  skill_type text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tags (
  id integer generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id integer generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null,
  button_link text,
  button_text text,
  icon text,
  json_id text,
  image_src text,
  video_src text,
  alt_text text,
  serial integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projecttags (
  project_id integer not null references public.projects(id) on delete cascade,
  tag_id integer not null references public.tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (project_id, tag_id)
);

create table if not exists public.publications (
  id integer generated by default as identity primary key,
  title text not null,
  venue text not null,
  year integer not null check (year between 1900 and 2100),
  link text,
  link_text text,
  type text,
  citation_count integer not null default 0,
  description text,
  json_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.researchcontent (
  id integer generated by default as identity primary key,
  title text not null,
  description text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.publicationtags (
  publication_id integer not null references public.publications(id) on delete cascade,
  tag_id integer not null references public.tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (publication_id, tag_id)
);

create table if not exists public.awards (
  id integer generated by default as identity primary key,
  title text not null,
  organization text not null,
  year integer not null check (year between 1900 and 2100),
  description text,
  image_url text,
  url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contactinfo (
  id integer generated by default as identity primary key,
  title text not null,
  description text not null,
  email text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.researchprofiles (
  id integer generated by default as identity primary key,
  name text not null,
  link text not null,
  icon text,
  bg_color text,
  text_color text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  content text not null,
  excerpt text,
  author text not null,
  status text not null default 'draft' check (status in ('draft', 'published')),
  image_url text,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id integer generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.books (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  description text,
  author text not null,
  isbn text,
  publisher text,
  page_count integer,
  image_url text,
  link text,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.news_articles (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  publication_name text not null,
  publication_logo_url text,
  article_url text not null,
  published_date date not null,
  author_name text,
  thumbnail_url text,
  category text,
  is_featured boolean not null default false,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_aboutexpertise_about_id on public.aboutexpertise(about_id);
create index if not exists idx_professionalexperience_resume_id on public.professionalexperience(resume_id);
create index if not exists idx_experienceresponsibilities_experience_id on public.experienceresponsibilities(experience_id);
create index if not exists idx_education_resume_id on public.education(resume_id);
create index if not exists idx_skills_resume_id on public.skills(resume_id);
create index if not exists idx_projects_serial on public.projects(serial);
create index if not exists idx_projecttags_tag_id on public.projecttags(tag_id);
create index if not exists idx_publications_year on public.publications(year desc);
create index if not exists idx_publicationtags_tag_id on public.publicationtags(tag_id);
create index if not exists idx_blog_posts_status_published_at on public.blog_posts(status, published_at desc);
create index if not exists idx_blog_posts_slug on public.blog_posts(slug);
create index if not exists idx_books_status_published_at on public.books(status, published_at desc);
create index if not exists idx_books_slug on public.books(slug);
create index if not exists idx_news_articles_published_date on public.news_articles(published_date desc);
create index if not exists idx_messages_created_at on public.messages(created_at desc);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'portfolioowner',
    'navigationitems',
    'herocontent',
    'herosubtitles',
    'heroctas',
    'aboutcontent',
    'aboutexpertise',
    'resume',
    'professionalexperience',
    'experienceresponsibilities',
    'education',
    'skills',
    'tags',
    'projects',
    'publications',
    'researchcontent',
    'awards',
    'contactinfo',
    'researchprofiles',
    'blog_posts',
    'messages',
    'books',
    'news_articles'
  ] loop
    execute format('drop trigger if exists trg_%I_set_updated_at on public.%I', table_name, table_name);
    execute format(
      'create trigger trg_%I_set_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      table_name,
      table_name
    );
  end loop;
end;
$$;

-- Supabase Row Level Security.
-- Public pages can read portfolio data. Logged-in admin users can manage it.
-- Anyone can submit a contact message; only authenticated users can read/update/delete messages.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'portfolioowner',
    'navigationitems',
    'herocontent',
    'herosubtitles',
    'heroctas',
    'aboutcontent',
    'aboutexpertise',
    'resume',
    'professionalexperience',
    'experienceresponsibilities',
    'education',
    'skills',
    'tags',
    'projects',
    'projecttags',
    'publications',
    'researchcontent',
    'publicationtags',
    'awards',
    'contactinfo',
    'researchprofiles',
    'blog_posts',
    'books',
    'news_articles'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists "public read" on public.%I', table_name);
    execute format('drop policy if exists "authenticated manage" on public.%I', table_name);
    execute format('create policy "public read" on public.%I for select using (true)', table_name);
    execute format('create policy "authenticated manage" on public.%I for all to authenticated using (true) with check (true)', table_name);
  end loop;
end;
$$;

alter table public.messages enable row level security;
drop policy if exists "public insert messages" on public.messages;
drop policy if exists "authenticated manage messages" on public.messages;
create policy "public insert messages"
on public.messages
for insert
to anon, authenticated
with check (true);

create policy "authenticated manage messages"
on public.messages
for all
to authenticated
using (true)
with check (true);

-- Minimal seed rows required by .single() calls and admin edit forms.
insert into public.portfolioowner (id, name, email, linkedin_url, github_url)
values (1, 'Shariful Haque', 'you@example.com', '', '')
on conflict (id) do nothing;

insert into public.herocontent (id, title, span, description)
values (
  1,
  'Shariful Haque',
  '',
  'Independent researcher and technology leader focused on AI, blockchain, data analytics, and ERP systems.'
)
on conflict (id) do nothing;

insert into public.herosubtitles (id, subtitle_text)
values
  (1, 'Researcher'),
  (2, 'Data Analyst'),
  (3, 'Blockchain Innovator'),
  (4, 'Author')
on conflict (id) do nothing;

insert into public.heroctas (id, text, link, icon)
values
  (1, 'View Research', '/#research', 'arrow-right-circle'),
  (2, 'Contact Me', '/#contact', null)
on conflict (id) do nothing;

insert into public.navigationitems (id, text, link, is_button)
values
  (1, 'About', '/#about', false),
  (2, 'Resume', '/#resume', false),
  (3, 'Research', '/#research', false),
  (4, 'Projects', '/#projects', false),
  (5, 'Awards', '/#awards', false),
  (6, 'Contact', '/#contact', true)
on conflict (id) do nothing;

insert into public.aboutcontent (
  id,
  title,
  description,
  image_src,
  image_alt,
  expertise_title,
  cta_text,
  cta_link,
  cta_icon
)
values (
  1,
  'About',
  'Add your professional biography from the admin panel.',
  '',
  'Portrait',
  'Areas of Expertise',
  'Contact Me',
  '/#contact',
  'arrow-right'
)
on conflict (id) do nothing;

insert into public.resume (id, title, intro, cv_download_text, cv_download_link)
values (1, 'Resume', 'Add your experience, education, and skills from the admin panel.', 'Download CV', '')
on conflict (id) do nothing;

insert into public.contactinfo (id, title, description, email, phone)
values (1, 'Get In Touch', 'Have a project in mind or just want to say hi? I would love to hear from you.', 'you@example.com', '')
on conflict (id) do nothing;

insert into public.researchcontent (id, title, description)
values (1, 'Research & Publications', 'My contributions to the academic community.')
on conflict (id) do nothing;

-- Optional starter tags for project/publication forms.
insert into public.tags (name)
values
  ('AI'),
  ('Blockchain'),
  ('Data Analytics'),
  ('ERP'),
  ('Research')
on conflict (name) do nothing;

-- Keep identity sequences ahead of the explicit seed ids.
select setval(pg_get_serial_sequence('public.portfolioowner', 'id'), coalesce((select max(id) from public.portfolioowner), 1), true);
select setval(pg_get_serial_sequence('public.navigationitems', 'id'), coalesce((select max(id) from public.navigationitems), 1), true);
select setval(pg_get_serial_sequence('public.herocontent', 'id'), coalesce((select max(id) from public.herocontent), 1), true);
select setval(pg_get_serial_sequence('public.herosubtitles', 'id'), coalesce((select max(id) from public.herosubtitles), 1), true);
select setval(pg_get_serial_sequence('public.heroctas', 'id'), coalesce((select max(id) from public.heroctas), 1), true);
select setval(pg_get_serial_sequence('public.aboutcontent', 'id'), coalesce((select max(id) from public.aboutcontent), 1), true);
select setval(pg_get_serial_sequence('public.resume', 'id'), coalesce((select max(id) from public.resume), 1), true);
select setval(pg_get_serial_sequence('public.contactinfo', 'id'), coalesce((select max(id) from public.contactinfo), 1), true);
select setval(pg_get_serial_sequence('public.researchcontent', 'id'), coalesce((select max(id) from public.researchcontent), 1), true);
select setval(pg_get_serial_sequence('public.tags', 'id'), coalesce((select max(id) from public.tags), 1), true);
