-- Run this only if you already ran supabase-rebuild-schema.sql before
-- the researchcontent table was added.

create table if not exists public.researchcontent (
  id integer generated by default as identity primary key,
  title text not null,
  description text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_researchcontent_set_updated_at on public.researchcontent;
create trigger trg_researchcontent_set_updated_at
before update on public.researchcontent
for each row
execute function public.set_updated_at();

alter table public.researchcontent enable row level security;

drop policy if exists "public read" on public.researchcontent;
drop policy if exists "authenticated manage" on public.researchcontent;

create policy "public read"
on public.researchcontent
for select
using (true);

create policy "authenticated manage"
on public.researchcontent
for all
to authenticated
using (true)
with check (true);

insert into public.researchcontent (id, title, description)
values (1, 'Research & Publications', 'My contributions to the academic community.')
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.researchcontent', 'id'), coalesce((select max(id) from public.researchcontent), 1), true);
